# Generated by Django 3.2.21 on 2023-09-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent', models.ImageField(blank=True, null=True, upload_to='uspto_figures/segmented_50000_v4/')),
            ],
        ),
    ]
